### ISSUE TITLE
Zsim support for near data processing

### ISSUE THREAD

**Issue by akgun1** [s5z/zsim#150]
Hello, I am exploring simulators for my research and I came across the papers on near data processing by @gaomy3832 @grantae , using zsim. I was wondering if zsim will integrate these changes in the near future.. Any guidance in terms of implementation of such a system is appreciated.

**Comment by gaomy3832** [comment]
We do have the plan to open source our code and potentially merge back to the main stream. We (the Stanford group) are talking with the MIT group about this, but since the code is developed and frequently updated on both sides, merging them is not trivial. So currently there is no exact timeline for this, thus no guarantee on the available time.

In terms of implementation of an NDP system like ours, there are several parts needed. First you need a better network model to capture the remote accesses, and integrate it into the memory hierarchy (potentially non-coherent). Second, you need to have an address mapping to distinguish local and remote (and which remote vault/cube) accesses. Or alternatively you can use explicit magic op in zsim to specify remote accesses, and make the default to be local. Third, define the API and put them into your workloads. These can be done through magic ops or PIN routine instrumentation.

**Comment by akgun1** [comment]
Thanks for the guidance!
