### ISSUE TITLE
Debugging workflow - Is using an IDE instead of xterm feasible?

### ISSUE THREAD

**Issue by dhiraj113** [s5z/zsim#161]
What is the typical debugging workflow that is being used to comprehend and debug zsim code. I have gotten an xterm based gdb debugging session by compiling with `scons --d` and running with `attachdebugger = True`. 

While this is very useful it's much less convenient than an IDE based debugging workflow. Looking at the code and as to how the debugging session is forked from the `launchXtermDebugger` function while also passing command line arguments to gdb via the parent process, I can see why it would be non-trivial to use an IDE and get it to attach to launched processes from zsim.

In this regard,  I am curious to know if anybody is successful in getting an IDE based debugging workflow to work? Or, is using the xterm based debugging workflow the best that could be done?

**Comment by gaomy3832** [comment]
I think the difficulty is the present of Pin tool. Pin is not fully open sourced at the first place. The way we start a task thread is launching through Pin, not a typical way. And we have three part in the simulator: Pin, user task threads, zsim threads which work as Pin instrumentation functions and analysis functions. All these make traditional debug tools hard to work with zsim. I am not an expert on gdb or other tools, so I don't know how practical to make a better workflow. But I hope this information can be helpful for others who want to try.

Another issue is that, since Pin is not open sourced, I found that when the stack trace reach into Pin, it does not provide useful information (maybe I compiled Pin in a wrong way). So if the bug is not in the instrumentation/analysis functions, but in the interaction between Pin and user threads, the debugging tools cannot help.

Anyway, I also look forward to a patch that can make the debug flow easier. That would be greatly helpful!

**Comment by dhiraj113** [comment]
@gaomy3832 Thanks for the information. So, essentially the zsim simulator (`libzsim.so)` is a pintool and hence can only be debugged the way pintools can be.

https://software.intel.com/sites/landingpage/pintool/docs/49306/Pin/html/index.html#DEBUGGING

The above link sought of explains why the `launchXtermDebugger` function explicitly passes the symbol table of the pintool `libzsim.so` using `add-symbol-file`.

On a side note, have you been able to set breakpoints inside the `libdramsim.so` library (or any shared library linked to `libzsim.so`)? I am not able to and I believe it can't be done without explicity passing the symbol table for `libdramsim.so` library as well in the `launchXtermDebugger` function.

**Comment by gaomy3832** [comment]
I agree with you. I haven't tried to debug `libdramsim.so` as I usually use our in-house DRAM simulator. I think it is do-able to pass the symbol table for `libdramsim.so` explicitly in the same way as `libzsim.so` by modifying `launchXtermDebugger`. Not sure how tricky it is, but you are welcomed to contribute a patch (just remember that DRAMSim2 is not always linked so use conditional macro to project it).
