### ISSUE TITLE
zsim stats: cycles (core) and total latency  (mem)

### ISSUE THREAD

**Issue by heojun18** [s5z/zsim#185]
Hello, 

I have some questions about zsim stats

1. Does "cycles" in core stats include memory access latency?
2. I have found that the sum of rdlat and wrlat in memory stats is greater than the sum of cycles in core stats. Are the units of "cycles" in core stats and "lat" in memory stats different?
3. Is the sum of "cycles" in core stats equal to the total cycles taken when the program in run?

Thank you!

**Comment by gaomy3832** [comment]
1. Cycles in core stats include memory latency.

2. rdlat and wrlat are simply the sum of the latency of all memory accesses. They do not consider the overlapping (parallelism) of these accesses. So they are not very useful to estimate performance.

3. For single-threaded simulation it is. But in the case of multi-threaded, there will be some timing difference due to synchronization between threads. You can also refer to "phases" for the total execution time.

**Comment by heojun18** [comment]
Thank you!
