### ISSUE TITLE
Fast forward in multicore system

### ISSUE THREAD

**Issue by shuzihua** [s5z/zsim#27]
Hi all.
I configured the simulator with 4 cores, and I set each process to first fast forward 40000000000 instructions and then simulate 10000000000 instructions by add the following 2 lines into each process's confiuration section:
    ffiPoints = "40000000000 10000000000";
    startFastForwarded = true;
My quetion is that is it possible that some processes have already finished simulation while others are still in fast forward? If so, how can I avoid this situation.
Another thing that confused me is that how are these processes scheduled on these 4 cores, I mean if I have 4 cores and 4 processes, is each process scheduled on a different core statically?
Thank you very much.

**Comment by s5z** [comment]
Yes, by default processes can exit fast-forwarding and start running while other processes are still fast-forwarding. Use the syncedFastForward flag to make all processes that exit fast-fwd wait until all processes have joined to start simulation. syncedFastFordward is not the default because it can cause deadlocks with more complex setups (e.g., a parent and child process that communicate through a pipe).

The scheduler tries to work on the principle of least surprise: so long as the processes don't have more threads than cores, it will spread threads among cores and keep them there. It will do simple round-robin scheduling every sim.schedQuantum phases if there are more threads than cores. In principle, every thread can be scheduled in any core. If you need finer control (e.g. restricting the threads of each process to a quadrant of the chip), use process masks (processX.procMask).
