### ISSUE TITLE
MPI applications in zsim

### ISSUE THREAD

**Issue by zoombull** [s5z/zsim#29]
Hello,

I have an issue running MPI application in zsim on a cluster. For some processes I get an error:
"libzsim.so address mismatch! text:  0x2aaaac60cd10 != 0x2aaaabcdcd10. Perform loader injection to homogenize offsets!"
After this, simulation gets stalled... 

Did anybody have similar problems or does anybody have any suggestions for running MPI applications in zsim?

Thanks,
Darko

**Comment by s5z** [comment]
You're trying to run a multi-process simulation, and for whatever reason, libzsim.so gets loaded at different offsets in different processes. Because there's a global memory pool that has objects with pointers to libzsim.so (e.g., vtables), all processes must load libzsim.so at the same spot. Pin typically does this without much fuss, but sometimes fails for a variety of reasons. Some things you can try:
- Recompile your programs and link them statically
- Do not mix statically-linked and dynamically-linked programs
- If you're using dynamically-linked programs, they may be using different loaders, which we've observed is the main cause for mismatches in memory layout. As the comment says, try processX.loader = "/usr/bin/ld" or whatever other loader you have in your system. Alternatively, modify the .interp ELF section in all the programs you use to use the same loader (this is cleaner and does not require having the source code, you can do it with patchelf or other simple tools)
- If you have processes creating other processes, and have a lot of environment variables or use long lists of arguments, they will take extra pages in the stack and may cause the child's libraries to be loaded somewhere else. Use an environment with as few variables as possible, and avoid long directory names and programs with many arguments.
- Try some of the more esoteric Pin command line switches to control the memory layout (separate memory, etc, see the Pin reference). You can add these through sim.pinOptions.
- Check that you're not running with address space layout randomization (zsim disables it by default, see the calls to personality(), but you may be running on some Linux flavor that behaves weirdly or might have set sim.aslr).

If you find a fix, please post back. If none of these do the trick, you're basically out of luck. Allowing copies of libzsim.so at different addresses would require avoiding virtual functions and RTTI on zsim or using some other, more mediated form of shared memory, which would require rewriting a large part of the code.

**Comment by zoombull** [comment]
Thanks for the response.
For some reason, it was due to the application I was running. I recompiled the application with openmpi, instead of Intel's library, and now everything works...
I tried some other MPI applications compiled with Intel's library and they work, so it is a bit strange and was related to the application and not zsim.

Thanks!
Darko

**Comment by andrewbartolo** [comment]
Adding my solution to this problem in case anyone runs across --

When running MPI applications, there are *two* distinct things that can cause libzsim.so to not be loaded at the same address across multiple worker processes. The first of these is ASLR -- it needs to be disabled, either at the kernel level by setting `/proc/sys/kernel/randomize_va_space` to 0, or, if you don't have root, you can write a wrapper program that disables ASLR via a call to `personality()` and then `execvp()`s the original binary. Zsim already has functionality to do this for processes that it launches (see zsim_harness.cpp).

The second thing that can cause libzsim.so address mismatches, which appears is happening here, is that `mpiexec` uses `dlopen()` to dynamically load MPI plugins (shared objects) at runtime. At least on OpenMPI, this process isn't deterministic, so different MPI plugins get loaded at different regions of memory, even with ASLR disabled. You can confirm this by running the `pmap` utility on the MPI worker processes' PIDs.

In theory, this shouldn't be a problem, but when Pin tries to load libzsim.so, the address where libzsim.so ends up being loaded seems to depend on the location and order in which the process's other shared objects were previously loaded. Hence, the nondeterminism in (Open)MPI's dlopen() phase is causing Pin to load libzsim.so in a nondeterministic way as well.

Pin also claims to give you some control over where the pintool gets loaded, via its "-pin_memory_range" and "-restrict_memory" flags (which replaced "-separate_memory," which Daniel mentions above, in pintool v. 67254 and later). I tried all three of these flags, "-separate_memory" with Pin 2.10, and the other two with Pin 2.14, and couldn't get any of them to load libzsim.so at the address I'd specified.

**The solution I've found** is to use a custom version of (Open)MPI and its mpiexec, built with the "--disable-shared", "--enable-static", and "--disable-dlopen" flags. The first two may not be strictly necessary, but I'm fairly certain the "--disable-dlopen" build option will prevent the nondeterministic behavior. Of course, this prevents (Open)MPI from dynamically loading plugins at runtime, but it seems to be a necessary tradeoff.

P.S. -- To determine which of the two scenarios is causing the mismatches, check the differing addresses. True kernel ASLR will load libzsim.so at addresses differing by a huge amount, e.g. `0x7f0000000000 != 0x7f9876543210`, whereas the `dlopen()` nondeterminism will cause much smaller differences, e.g., the `0x2aaaac60cd10 != 0x2aaaabcdcd10` that you saw.
