### ISSUE TITLE
synced fast forward philosophy and behavior

### ISSUE THREAD

**Issue by gaomy3832** [s5z/zsim#46]
I find the behavior of synced fast forward is a little confusing. First, what is its purpose? #27 said it is used between processes. Does it have any impact on single-process, multi-threaded program?

#27 also said syncedFastForward should not be the default behavior. But in the cfg file if we don't specify it, the default is true, as in https://github.com/s5z/zsim/blob/master/src/process_tree.cpp#L175.

The main problem with syncedFastForward enabled is for ROI end operation, as in https://github.com/s5z/zsim/blob/master/src/zsim.cpp#L1158-1159. ROI end will be completely ignored. However, the lines below it are also confusing, as the branch in line 1166 will never enter given line 1158. The inline comments and #27 explained that this is to avoid deadlock. I think we should either change the default syncedFastForward value or come up with a better mechanism for this.

Thanks!

**Comment by s5z** [comment]
We probably changed syncedFastForward to true by default at some point.

In practice, we use fast-forward in two cases. First, with multi-process simulations of single or multi-threaded workloads, where all programs fast-forward to the ROI. In these cases, syncedFastForward = true so that each process pauses when it reaches the ROI, and simulation resumes when all processes have reached it. In this case, termination is handled through some fixed condition, such as sim.maxEventualStatsDumps or sim.maxMinInstrs.

The second case is with complex multi-process workloads that are realted (eg a client/server app). Here you want to fast-forward the intialization, then externally (through fftoggle) or internally (in the programs themselves) detect when you've reached the ROI. Here, syncedFastForward = false, because typically you want to toggle one or two processes (eg the server and the client), and all others (eg bash scripts used to launch them or other daemons) are kept fast-forwarded throughout the simulation.

syncedFastForward does not depend on whether a program is single or multithreaded. It acts at the process level. You can't fast-forward some threads and simulate others (through this is possible with some modifications)

We have not run into a situation that requires syncedFastForward and ROI end, hence why there's no mechanism to handle this. If you have a use case that needs this, I'm open to fixes. We can also revert the default (though I'd rather have a default that deadlocks or misbehaves visibly and forces the user to learn about the feature, rather than a default that silently causes skew in multi-process simulations).

**Comment by gaomy3832** [comment]
Usually my application has only one process. But I would like to use ROI begin/end to mark and fast forward certain parts of the program, such as loading input data, verifying results, etc..

I guess based on the current implementation, I should explicitly say syncedFastForward=false. But it will be much more convenient if the default behavior could work with my use case, as I think the common use case for the simulator is single process, i.e., for one certain application.

At the same time, I do agree with you about that we should not let it silently misbehaves. I am not sure what is the best way to improve this case. If you can suggest a fix, I am happy to try out a patch. If not, I can always explicitly specify, and we can close this issue.

Thanks!

**Comment by s5z** [comment]
How about having syncedFastForward = "Multiprocess" | "Always" | "Never", with default "Multiprocess", which turns it on with multiple processes but leaves it off with a single process?
