### ISSUE TITLE
Cache inclusion policies

### ISSUE THREAD

**Issue by grantae** [s5z/zsim#62]
What is the current extent of support for inclusive, non-inclusive, and--to a lesser extent--exclusive caching policies?

From the source it appears that all caches are inclusive unless a non-terminal cache sets "nonInclusiveHack," in which case it is non-inclusive. (Why "hack"? Are there issues or limitations with this feature aside from being usable only with simple cache types?) Exclusive does not seem to be supported. Is this correct?

**Comment by kartikram3** [comment]
Yes there is no exclusive cache. I am guessing it is a non inclusive hack because it has not been tested extensively. From my use of non-inclusive hack, it seems to work most of the time. I do recall getting errors for particular configurations but they were pretty rare.

**Comment by grantae** [comment]
Thanks. By default is the inclusive property automatically applied to the LLC, and only to the LLC? It would seem strange if this is not the case because many common processors have non-inclusive L2 caches and an inclusive L3/LLC (e.g., recent Intel parts). If zsim is not automatically applying inclusivity to the last cache then I don't know how it would distinguish when to do it, and it would be incorrect (at least in principle) to model the L2 as inclusive.

**Comment by kartikram3** [comment]
All the cache levels are inclusive by default, not just the LLC.  You can make a desired level non inclusive using the non inclusive hack. In this case, you can specify nonInclusiveHack=true for the L2 cache.
I don't think zsim has any mechanism to automatically decide the clusion property of the cache levels.

**Comment by s5z** [comment]
All levels are inclusive by default. The flag is called nonInclusiveHack because it doesn't cover all use cases.

IIRC, nonInclusiveHack won't work in intermediate levels that need to keep children coherent (e.g., if you want private, non-inclusive L2s and a shared L3). This is because, on an invalidation, a cache with nonInclusiveHack set won't probe a child if it doesn't find the line in its own level.

nonInclusiveHack works fine with fully shared caches (e.g., a shared L3 followed with a shared non-inclusive L4). At that point, there's no need to probe children.

Internally, we've moved away from nonInclusiveHack, and have simple non-inclusive and exclusive cache models that do not use a coherence controllers, because beyond the lowest fully-shared cache level there's no need for cache coherence.

**Comment by grantae** [comment]
Great, thanks. It sounds like the limitation is that these cache modules only probe their direct children, and to remove the "hack" attribute they would need to probe all of their descendants to handle the case of non-inclusive children (e.g., L3 probes L2 AND L1 on an invalidation). I'll close the question based on this assumption. Thanks for the responses.
