### ISSUE TITLE
SMT on OoO cores

### ISSUE THREAD

**Issue by ugigugi** [s5z/zsim#71]
It's more a question than really an issue...

I am currently exploring different simulators to use for my research. zSim is a nice pick but I see that it doesn't support SMT in its core models. Do you plan in a near future to add that feature? If not, how complicated would it be to implement such a thing? Any advice is more than helpful.

Thanks a lot.

**Comment by s5z** [comment]
It is doable, though we do not plan on adding this feature in the near future, at least in the OOO core. You could ask Mingyu and Grant, who recently implemented fine-grain multithreading on zsim, for their code (see http://web.stanford.edu/~mgao12/pubs/ndp.pact15.pdf)

**Comment by gaomy3832** [comment]
Well, here I am :)

First, we only modeled MT on TimingCore, which is a single-issue, in-order core model. And the MT in our case is fine-grained MT (switch thread every cycle), not simultaneous MT (every cycle pick and issue the ready one). We sort of achieve our goal through a hacking way, for example for 2-way FMT, we double the number of cores, bring down the frequency to 1/2, then make each two cores sharing the L1 caches (which needs to add dummy L1 since zsim needs each core to connect to a private L1).

SMT is more complicated since you have to model the arbitrary logic to select and issue thread. And it becomes more complicated when moving to OoO, which has "out of order" scheduling. So I don't think a hack like we did makes sense in this case, and you have to modify the internal logic of OoO core model in zsim.

**Comment by ugigugi** [comment]
Ok guys, thanks a lot! I will let you know if we start with adding this feature to zSim just to be updated.
