### ISSUE TITLE
Replacement Policies in the L1I cache 

### ISSUE THREAD

**Issue by rprabala** [s5z/zsim#77]
I'm interested in modeling different replacement policies in the L1I cache. However, I noticed that since the L1I is directly connected to the core, it is required to be a FilterCache. The stats for a FilterCache are hardcoded in init.cpp. Was there a reason for this beyond simulation optimization? If I would like to explore other replacement policies in the L1I, do I need to disable this by modifying the code, or are there other ways to achieve this simulation effect?

**Comment by s5z** [comment]
FilterCache is mainly a performance optimization. It also is much more effective with simple cores (~3x faster), but not as dramatic on OOO cores.

FilterCache is essentially a direct-mapped L0 cache that captures the MRU line in each set of the L1. So if you use a replacement policy where an MRU hit does not require changing any replacement policy state (e.g., pseudoLRU or random), then you're all set. Otherwise, you can disable this feature and just have FilterCache as an adapter between the load()/store() interface to the cache's access()/invalidate() interface.
