### ISSUE TITLE
how to use valgrind to check memory leak in zsim

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#96]
hello,

       I am doing some work based on zsim. However, modified simulation will be teminated due to panic "[S 0] Panic on build/opt/galloc.cpp:133: gm_malloc(): Out of global heap memory, use a larger GM s    egment" , I think it maybe caused by memory leak, so I want to use valgrind to check memory leak issues. When I run command, "valgrind --tool=memcheck --log-file=memcheck.log --leak-check=full ./zsim test.cfg", memory checking always terminated due to "[H] Panic on build/opt/zsim_harness.cpp:301: Could not exec /home/chenyujie/zsim-nvmain/pin_kit/intel64/bin/pinbin". Can I use valgrind to check memory leak problems in zsim? Looking forward to your kindly response!

**Comment by gaomy3832** [comment]
I haven't used valgrind with zsim. It might be a little complicated. But on the other hand, it may be the case that your extension does need a lot of global memory. You can increase the size of the global memory to work around this by assign `sim.gmMBytes` in cfg file, such as 

```
sim = {
    gmMBytes = 2048;
};
```

If a large number (like 4096 or 8192) still doesn't resolve the problem, then it is very likely you do have some memory leakage.

**Comment by s5z** [comment]
Using valgrind here is about as hard as it gets. First, you'd be instrumenting Pin under valgrind, two levels of dynamic binary instrumentation. Second, you have three memory allocators: the application's, Pin's, and zsim's. And zsim's allocations go to a shared memory segment.

If you have a leak, I'd instrument zsim's memory allocator to find where it's coming from instead of trying valgrind.

**Comment by cyjseagull** [comment]
Thank you very much ! Your replies have helped me a lot !
